"""empty message

Revision ID: 5e15801288a0
Revises: d0791bcf1768
Create Date: 2025-09-12 15:17:42.019855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5e15801288a0'
down_revision: Union[str, Sequence[str], None] = 'd0791bcf1768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('id_shelves',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('id_categorys',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('documents_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('documents_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'shelves', ['id_shelves'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'categorys', ['id_categorys'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('documents_ibfk_2'), 'shelves', ['id_shelves'], ['id'])
        batch_op.create_foreign_key(batch_op.f('documents_ibfk_1'), 'categorys', ['id_categorys'], ['id'])
        batch_op.alter_column('id_categorys',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('id_shelves',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
