"""empty message

Revision ID: b67fe7995d0d
Revises: e0667d7f43c1
Create Date: 2025-09-11 14:52:50.915239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67fe7995d0d'
down_revision: Union[str, Sequence[str], None] = 'e0667d7f43c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userinfo_email'))
        batch_op.create_index(batch_op.f('ix_userinfo_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userinfo_email'))
        batch_op.create_index(batch_op.f('ix_userinfo_email'), ['email'], unique=True)

    # ### end Alembic commands ###
