"""empty message

Revision ID: d0791bcf1768
Revises: b67fe7995d0d
Create Date: 2025-09-12 15:15:55.166018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd0791bcf1768'
down_revision: Union[str, Sequence[str], None] = 'b67fe7995d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_shelves', sa.Integer(), nullable=False),
    sa.Column('id_categorys', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categorys'], ['categorys.id'], ),
    sa.ForeignKeyConstraint(['id_shelves'], ['shelves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('shelves')
    op.drop_table('categorys')
    # ### end Alembic commands ###
