"""empty message

Revision ID: e0667d7f43c1
Revises: 61233ed47af3
Create Date: 2025-09-11 14:51:42.523732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0667d7f43c1'
down_revision: Union[str, Sequence[str], None] = '61233ed47af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('ix_userinfo_email'), ['email'], unique=True)
        #batch_op.drop_constraint(batch_op.f('userinfo_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'localuser', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('userinfo_ibfk_3'), 'localuser', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_userinfo_email'))

    # ### end Alembic commands ###
